on:
  workflow_call:
    inputs:
      extensionName:
        description: 'Your extension name'
        required: true
        type: string
      shopwareVersion:
        required: false
        type: string
        default: 'trunk'
env:
  SHOPWARE_TOOL_CACHE_ECS: ${{ github.workspace }}/var/cs_fixer
jobs:
  run:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Clone Shopware
        uses: actions/checkout@v4
        with:
          repository: "shopware/shopware"
          ref: ${{ inputs.shopwareVersion }}
      - name: Install Composer Dependencies
        working-directory: vendor-bin/cs-fixer
        run: composer install
      - name: Clone Extension
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ inputs.extensionName }}
      - name: ECS cache
        uses: actions/cache@v3
        with:
          path: ${{ env.SHOPWARE_TOOL_CACHE_ECS }}
          key: ${{ runner.OS }}-${{ github.repository }}-ecs-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-ecs-
      - name: Run ECS
        run: ${{ github.workspace }}/vendor-bin/cs-fixer/vendor/bin/ecs check custom/plugins/${{ env.PLUGIN_NAME }}
